### ISSUE TITLE
Test1

### ISSUE THREAD

**Issue by Dulotar0** [Dulotar0/practicaGestor-presupuesto#1]
@pedroprieto Buenas.
He terminado de hacer Fundamentos de JS II y me falla el test1 en la parte de mostrar los gastos, entiendo que es normal porque para el test 2 hay que cambiar el formato verdad?

**Comment by pedroprieto** [comment]
Buenas,

No, deben pasarse los dos a la vez. Te falla el I porque no has creado la función `mostrarGasto`, que es diferente de `mostrarGastoCompleto`. Añádela y comprueba que funciona :wink:

**Comment by Dulotar0** [comment]
Vale vale entiendo, pense que era actualizar la funcion, ya esta arreglado.
