### ISSUE TITLE
Error al sumar totales

### ISSUE THREAD

**Issue by Dulotar0** [Dulotar0/practicaGestor-presupuesto#2]
Buenas.
@pedroprieto
Estoy haciendo la introduccion a JSIII, que despues de la clase de ayer tengo mas claro como funciona el reduce, pero tengo un error y no se bien que me quiere decir el codigo de error.
![imagen_2024-10-24_103821633](https://github.com/user-attachments/assets/3b4bcc31-c925-4491-9455-6a2909ab5326)
En pantalla se ve el resultado de la funcion de agrupar gastos. pone que falla al sumar el total por mes, que el expected es 22.8 y supuestamente si esta.
Es porque estan ordenados al reves?
Gracias de antemano.

**Comment by pedroprieto** [comment]
Buenas,

Está casi perfecto. Lo que ocurre es que el ejemplo que os puse yo ayer devuelve una estructura diferente de lo que pide el ejercicio. El ejercicio pide devolver una estructura como esta:
```js
{
    "2021-09": 22.8,
    // Etcétera
}
```

Tú estás generando una estructura como esta:
```js
{
    "2021-09": {contador: 1 , listado: [/*elementos*/], total: 22.8},
    // Etcétera
}
```

Es decir, lo de ayer no era la solución al ejercicio tal cual. Tienes que modificarlo para que en lugar de almacenar para cada mes (en este caso) un objeto con `contador`, `listado` y `total`, almacene solo el total y quede como pone el enunciado. El test se queja de eso: si te fijas, está comparando un objeto con un número, por eso no coincide y da fallo. Tienes que almacenar el número, no el objeto completo.

Prueba y me cuentas :wink:

**Comment by Dulotar0** [comment]
Justo lo acabo de resolver jeje, me ha costado poner el total a la propiedad de la fecha, porque me lie poniendo mas informacion de la necesaria
