### ISSUE TITLE
Error objeto no extensible

### ISSUE THREAD

**Issue by Dulotar0** [Dulotar0/practicaGestor-presupuesto#3]
Buenas, estoy haciendo la 4 practica y me esta saliendo un error que no entiendo mucho
![image](https://github.com/user-attachments/assets/6a45425e-a876-4602-af6c-f0e311852dbe)
he estado mirando pero no se donde puede dar error la verdad 
![image](https://github.com/user-attachments/assets/cb95996e-33e4-47bc-b96b-0a4a65d43efd)
asi genero los datos y luego la funcion CrearGastos me pasa todos los tests, lo cual no se, directamente me salta el error al entrar en CrearGastos

**Comment by Dulotar0** [comment]
@pedroprieto, no te mencione jeje

**Comment by pedroprieto** [comment]
Para estos errores, es mejor lanzar la aplicación con la extensión `Live Server` de VS Code y ver la consola del navegador, a ver qué errores aparecen.

Si subes los cambios a GitHub le puedo echar un ojo al código y te puedo ayudar. Avísame cuando lo hayas hecho.

Un saludo!

**Comment by Dulotar0** [comment]
ay que no subi los cambios perdona, y si que vi la consola del navegador pero salia un error directamente

**Comment by Dulotar0** [comment]
ya estan subidos

**Comment by pedroprieto** [comment]
Estas rutas están mal:
https://github.com/Dulotar0/practicaGestor-presupuesto/blob/35658cc1a14b86ee7a459d044c124ece822fa64e/js/generarDatosEstaticos.js#L1-L2

Deben empezar por `./` (están en la misma carpeta que `generarDatosEstaticos.js`)

Aparte, `CrearGasto` es un constructor: debes llamarlo con `new`:
https://github.com/Dulotar0/practicaGestor-presupuesto/blob/35658cc1a14b86ee7a459d044c124ece822fa64e/js/generarDatosEstaticos.js#L7

Un saludo!
