### ISSUE TITLE
Problema cargando datos

### ISSUE THREAD

**Issue by Dulotar0** [Dulotar0/practicaGestor-presupuesto#5]
buenas @pedroprieto
Estoy teniendo un fallo en la función de cargar gastos del GestionPresupuesto, o eso creo.
Por alguna razón, al darle a cargar se me cargan un montón de gastos completamente vacíos, no se si en la función crearGastos() hay que añadir cosas o con el código que nos das en el enunciado es suficiente, he usado el código que nos das y me da error.

**Comment by pedroprieto** [comment]
Buenas,

Por lo que he visto, no utilizas los métodos `getItem` y `setItem` de `localStorage`...

**Comment by Dulotar0** [comment]
Donde? Es que no esto entendiendo mucho, la función de crearGastos(gastosAlmacenamiento) dentro de gestionPresupuesto hay que cambiarla?

**Comment by Dulotar0** [comment]
ya lo termine aunque no se si como querias
